# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://suraj.io/"
DefaultContentLanguage  = "en"
title                   = "Suraj Deshmukh"
theme                   = "hugo-future-imperfect-slim"
paginate                = 10
disqusShortname         = "suraj-io"
googleAnalytics         = "UA-97006720-1"
pluralizeListTitles     = false
disableLanguages        = [""]

[outputs]
  home                  = ["html", "json"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml", "shell", "bash", "go"]
  viewMorePostsLink     = "/post/"
  readingTime           = true
  socialShare           = ["twitter", "reddit", "linkedin", "facebook", "email"]

  [params.meta]
    description         = "Blog"
    author              = "Suraj Deshmukh"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Suraj Deshmukh"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true

  [params.intro]
    header                = "Blog"
    paragraph             = "containers, programming, golang, hacks, kubernetes, productivity, books"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "https://github.com/surajssd.png"
      shape               = "square"
      width               = ""
      alt                 = "Suraj Deshmukh"

  [params.sidebar]
    about               = "I am a Senior Software Engineer at Microsoft, working on various tooling around container technology like Docker, Kubernetes, etc."
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = true
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/post/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5

  # [[menu.main]]
  #   name              = "Contact"
  #   identifier        = "contact"
  #   url               = "/contact/"
  #   pre               = "<i class='far fa-envelope'></i>"
  #   weight            = 6

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1


[social]
  # Coding Communities
  github                = "surajssd"
  # gitlab                = ""
  stackoverflow         = "3848679/surajd" # User Number
  # bitbucket             = ""
  # jsfiddle              = ""
  # codepen               = ""
  # Visual Art Communities
  # deviantart            = ""
  # flickr                = "example"
  # behance               = ""
  # dribbble              = ""
  # Publishing Communities
  wordpress             = "deshmukhsuraj"
  # medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = "suraj-deshmukh-0205b834"
  # linkedin_company      = "examplebusiness"
  # foursquare            = ""
  # xing                  = ""
  slideshare            = "surajssd009005"
  # Social Networks
  # facebook              = "example"
  # googleplus            = ""
  # reddit                = "example"
  # quora                 = ""
  youtube               = "surajssd009005"
  # vimeo                 = ""
  # whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    # wechat              = ""
    # qq                  = "" # User ID Number
  # instagram             = "example"
  # tumblr                = ""
  twitter               = "surajd_"
  # strava                = ""
  # skype                 = ""
  # snapchat              = ""
  # pinterest             = "example"
  # telegram              = "example"
  # vine                  = ""
  # googlescholar         = ""
  # orcid                 = ""
  # researchgate          = "example"
  # keybase               = "example"
  # mastodon              = "example.com/@example"
  # Email
  email                 = "surajd.service@gmail.com"
